### ISSUE TITLE
Composable design system

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/pluraltools-frontend#585]
## overview
Make composable in colours, logos, fonts (design system)

**Comment by camilovegag** [comment]
Use css root variables with a theme provider to change the colours and fonts

Load on admin the hex and the fonts and see live changes of the template (as we do with emails)

```css
  const themes = {
    light: {
      backgroundColor: '#ffffff',
      textColor: '#222222',
      gray: '#bbbbbb',
      darkGray: '#cccccc',
    },
    dark: {
      backgroundColor: '#222222',
      textColor: '#ffffff',
      gray: '#777777',
      darkGray: '#888888',
    },
  };
```
